# Generated by Django 4.2.5 on 2023-09-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storagecap', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.signup')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.item')),
            ],
        ),
    ]
